export const GET_FILMS = "GET_FILMS";
export const GET_SINGLE_FILM = "GET_SINGLE_FILM";
export const GET_STARSHIPS = "GET_STARSHIPS";
export const GET_PLANETS = "GET_PLANETS";
export const FILTERED_FILMS = "FILTERED_FILMS";
export const CLEAR_FILTER = "CLEAR_FILTER";